### ISSUE TITLE
Install FontAwesome?

### ISSUE THREAD

**Issue by CookiBytes** [chrisblakely01/simple-shopping-list#1]
Hi,

I was doing your tutorial and copied-paste your starter code. When I ran `npm start`, it said to install fontawesome. I did using `npm i @fortawesome/free-solid-svg-icons`. So I looked at [http://localhost:3000/](http://localhost:3000/) and it said:

`Error: Cannot find module '@fortawesome/react-fontawesome'`

How can I fix this? Because there are several Font Awesome packages, and I don't know which one to install.

`@fortawesome/fontawesome-svg-core \`
`@fortawesome/free-solid-svg-icons \`
`@fortawesome/react-fontawesome`
`@fortawesome/free-solid-svg-icons`

Help would be very much appreciated,
~ CookiBytes

**Comment by CookiBytes** [comment]
Can someone help please? I still have this problem.

**Comment by chris-blakely-da** [comment]
Hey all the packages are included in the project by default - so when you clone the starter/final files, just run `npm install` and it will set everything up for you 👍

**Comment by CookiBytes** [comment]
> Hey all the packages are included in the project by default - so when you clone the starter/final files, just run `npm install` and it will set everything up for you 👍

Oh, okay. So I have to clone the project and then run `npm install`. Thanks!
